{% set version = "1.4-4" %}

package:
  name: r-rgdal
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/rgdal_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rgdal/rgdal_{{ version }}.tar.gz
  sha256: 2532e76e0af27d145f799d70006a5dbecb2d3be698e3d0bbf580f4c41a34c5d7

build:
  number: 0
  skip: True  # [win]
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - r-base
    - r-sp >=1.1_0
    - libgdal
    - proj4
  run:
    - r-base
    - r-sp >=1.1_0
    - libgdal
    - proj4

test:
  commands:
    - R -e "library('rgdal')"  # [not win]

about:
  home: http://www.gdal.org, https://r-forge.r-project.org/projects/rgdal/
  license: GPL-3.0
  summary: 'Provides bindings to Frank Warmerdam''s Geospatial Data Abstraction Library (GDAL)
    (>= 1.6.3) and access to projection/transformation operations from the PROJ.4 library.
    The GDAL and PROJ.4 libraries are external to the package, and, when installing
    the package from source, must be correctly installed first. Both GDAL raster and
    OGR vector map data can be imported into R, and GDAL raster data and OGR vector
    data exported. Use is made of classes defined in the sp package. Windows and Mac
    Intel OS X binaries (including GDAL, PROJ.4 and Expat) are provided on CRAN. '

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
