travis:
  secure:
    BINSTAR_TOKEN: EGPa+PE6tRz/cBWvHNjXu8ZSDStjomseVq1Bqb2K4xEU7EsZPfqtP50qlNJcMGeTE2N2whENp8/Sb0TvV1w8V6WrXYgbc/prNdnFqScDXZDbsdPQqDZjqF9sdQ3i92EoTyiuKbHTCXJW5atkyRia/HO0dB7uYJ47lKfvTBn3F5mTZ6NQWzhBBrkpSwktRcVYyRSMFaJQ0OGWm262fTQ5pqOXyqJkUpIzF2NtKXiYY7IwcXYejcDkRQPXSl5RF5znlI6taMUQbwivB5/BNT9++bY7rEdevdpoNw03ZisfDJdwCPwWAhtSZNC+lcCGbbbcFh4yzT6DfsRYgut9ysnFHloZGmWJvsKGuHYo7qZUl7XYgSfj7TB+blKwkvKJhmgKEBA43fFZPY47Askw728VJ5qKOff0RQrX/Wsglr87MH6jwByP65/vEQ0r+zXjYhq5ZLMqhkWBbmFhUwHpO17biKRurjVCAnW64QzmObw2i05yvRFmvDWdsZ/UC7KB8hwCw9xn0SRLAGXRyTOeK8rI8XNijgIzCYyHLQ9dB6l51//zxUHJzny7ll+NqltP1sa97Xd71tksoNNmvptWB6KjVpIhxKF+/F7Q8m3Mssw0+1e4oGsMJr0nRY5LGXT1/1bee/lw6OL9HFpOM50jxu0w4aOdkmIIiUTIwCHg22Sl/mY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
